products:

  fed_funds:
    product_code: ZQ
    display_name: Fed Funds Futures
    quote_format: price
    supported_timeframes:
      - 1M
      - 5M
      - 15M
      - 1H
      - 4H
      - 1D

    outright_tick_size: 0.005
    outright_tick_value: 20.835

    spread_tick_size_bp: 0.5
    spread_tick_value: 20.835

    contracts:
      - FFN26
      - FFQ26
      - FFU26
      - FFV26
      - FFX26
      - FFZ26
      - FFF27
      - FFG27
      - FFH27

    spreads:
      - FFN26-FFQ26
      - FFQ26-FFU26
      - FFU26-FFV26
      - FFV26-FFX26
      - FFX26-FFZ26
      - FFZ26-FFF27
      - FFF27-FFG27
      - FFG27-FFH27

  sofr:
    product_code: SR3
    display_name: SOFR Futures
    quote_format: price
    supported_timeframes:
      - 1M
      - 5M
      - 15M
      - 1H
      - 4H
      - 1D

    outright_tick_size: 0.0025
    outright_tick_value: 6.25

    spread_tick_size_bp: 0.25
    spread_tick_value: 6.25

    contracts:
      - SFRM26
      - SFRU26
      - SFRZ26
      - SFRH27

    spreads:
      - SFRM26-SFRU26
      - SFRU26-SFRZ26
      - SFRZ26-SFRH27
